# Generated by Django 3.0.3 on 2020-04-08 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerrank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrank',
            name='player_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerrank',
            name='point_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='point_app.Point'),
            preserve_default=False,
        ),
    ]
