# Generated by Django 3.0.3 on 2020-04-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_auto_20200408_0105'),
        ('playerrank_app', '0002_auto_20200408_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrank',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category_app.Category'),
            preserve_default=False,
        ),
    ]
