# Generated by Django 3.0.3 on 2020-04-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerrank_app', '0003_playerrank_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrank',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
