from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser,BaseUserManager
from django_countries.fields import CountryField
from phone_field import PhoneField
from .managers import ProfileManager
from django.db.models.signals import post_save
# Create your models here.
cityList = (
    ('Abadan','Abadan'),
    ('Abadeh','Abadeh'),
    ('Abarkuh','Abarkuh'),
    ('Abhar','Abhar'),
    ('Abyek','Abyek'),
    ('Ahar','Ahar'),
    ('Ahvaz [Ahvaz]','Ahvaz [Ahvaz]'),
    ('Ajab Shir','Ajab Shir'),
    ('Aleshtar','Aleshtar'),
    ('Ali Abad','Ali Abad'),
    ('Aligudarz','Aligudarz'),
    ('Alvand','Alvand'),
    ('Amirkola','Amirkola'),
    ('Amol','Amol'),
    ('Andimeshk','Andimeshk'),
    ('Andisheh','Andisheh'),
    ('Aq Qala','Aq Qala'),
    ('Arak','Arak'),
    ('Aran Va Bidgol','Aran Va Bidgol'),
    ('Ardabil','Ardabil'),
    ('Ardakan','Ardakan'),
    ('Asad-Abad','Asad-Abad'),
    ('Ashkhaneh','Ashkhaneh'),
    ('Astaneh-E Ashrafiyeh','Astaneh-E Ashrafiyeh'),
    ('Astara','Astara'),
    ('Azadshahr','Azadshahr'),
    ('Azarshahr','Azarshahr'),
    ('Azna','Azna'),
    ('Babol','Babol'),
    ('Babolsar','Babolsar'),
    ('Bafq','Bafq'),
    ('Baft','Baft'),
    ('Bagh-E Malek','Bagh-E Malek'),
    ('Baghestan','Baghestan'),
    ('Bahar','Bahar'),
    ('Baharestan','Baharestan'),
    ('Bam','Bam'),
    ('Bandar-E -Abas [Bandar Abbas]','Bandar-E -Abas [Bandar Abbas]'),
    ('Bandar-E Anzali','Bandar-E Anzali'),
    ('Bandar-E Deylam','Bandar-E Deylam'),
    ('Bandar-E Emam Khomeyni','Bandar-E Emam Khomeyni'),
    ('Bandar-E Ganaveh','Bandar-E Ganaveh'),
    ('Bandar-E Kangan','Bandar-E Kangan'),
    ('Bandar-E Lengeh [Bandar Lengeh]','Bandar-E Lengeh [Bandar Lengeh]'),
    ('Bandar-E Mahshahr','Bandar-E Mahshahr'),
    ('Bandar-E Torkaman','Bandar-E Torkaman'),
    ('Baneh','Baneh'),
    ('Baqershahr','Baqershahr'),
    ('Bardaskan','Bardaskan'),
    ('Bardsir','Bardsir'),
    ('Behbahan','Behbahan'),
    ('Behshahr','Behshahr'),
    ('Bijar','Bijar'),
    ('Birjand','Birjand'),
    ('Bojnurd','Bojnurd'),
    ('Bonab','Bonab'),
    ('Borazjan','Borazjan'),
    ('Borujen','Borujen'),
    ('Borujerd','Borujerd'),
    ('Bukan','Bukan'),
    ('Bumahen','Bumahen'),
    ('Bushehr','Bushehr'),
    ('Chabahar','Chabahar'),
    ('Chaharbagh','Chaharbagh'),
    ('Chahardangeh','Chahardangeh'),
    ('Chalus','Chalus'),
    ('Chamran','Chamran'),
    ('Chenaran','Chenaran'),
    ('Damavand','Damavand'),
    ('Damghan','Damghan'),
    ('Darab','Darab'),
    ('Dargaz','Dargaz'),
    ('Dehbarez (Rudan)','Dehbarez (Rudan)'),
    ('Dehdasht','Dehdasht'),
    ('Dehgolan','Dehgolan'),
    ('Dehloran','Dehloran'),
    ('Delijan','Delijan'),
    ('Dezful','Dezful'),
    ('Divandareh','Divandareh'),
    ('Dorcheh Piaz','Dorcheh Piaz'),
    ('Dowlat Abad','Dowlat Abad'),
    ('Dugonbadan [Dogonbadan]','Dugonbadan [Dogonbadan]'),
    ('Durud [Dorud]','Durud [Dorud]'),
    ('Eqbaliyeh','Eqbaliyeh'),
    ('Eqlid','Eqlid'),
    ('Isfahan','Isfahan'),
    ('Esfarayen','Esfarayen'),
    ('Eshtehard','Eshtehard'),
    ('Eslamabad-E Gharb','Eslamabad-E Gharb'),
    ('Eslamshahr','Eslamshahr'),
    ('Estahban','Estahban'),
    ('Falavarjan','Falavarjan'),
    ('Fardis','Fardis'),
    ('Fariman','Fariman'),
    ('Farokh Shahr','Farokh Shahr'),
    ('Farsan','Farsan'),
    ('Fasa','Fasa'),
    ('Ferdows','Ferdows'),
    ('Ferdowsieh','Ferdowsieh'),
    ('Fereydunkenar','Fereydunkenar'),
    ('Firuz-Abad','Firuz-Abad'),
    ('Fuladshahr','Fuladshahr'),
    ('Fuman','Fuman'),
    ('Garmsar','Garmsar'),
    ('Gerash','Gerash'),
    ('Germi','Germi'),
    ('Golbahar','Golbahar'),
    ('Goldasht','Goldasht'),
    ('Golestan (Soltanabad)','Golestan (Soltanabad)'),
    ('Golpayegan','Golpayegan'),
    ('Gonabad','Gonabad'),
    ('Gonbad-E Kavus [Gonbad-E Qabus]','Gonbad-E Kavus [Gonbad-E Qabus]'),
    ('Gorgan','Gorgan'),
    ('Hadishahr','Hadishahr'),
    ('Ḥaji Abad [Hajjiabad]','Ḥaji Abad [Hajjiabad]'),
    ('Hamadan','Hamadan'),
    ('Ḥamidiya','Ḥamidiya'),
    ('Harsin','Harsin'),
    ('Ḥasan Abad','Ḥasan Abad'),
    ('Hashtgerd','Hashtgerd'),
    ('Hashtpar','Hashtpar'),
    ('Hendijan','Hendijan'),
    ('Ilam','Ilam'),
    ('Iranshahr','Iranshahr'),
    ('Ivan','Ivan'),
    ('Izeh','Izeh'),
    ('Jahrom','Jahrom'),
    ('Jam','Jam'),
    ('Javanrud','Javanrud'),
    ('Jiroft','Jiroft'),
    ('Juybar','Juybar'),
    ('Kahnuj','Kahnuj'),
    ('Kahrizak','Kahrizak'),
    ('Kalaleh','Kalaleh'),
    ('Kamal Shahr','Kamal Shahr'),
    ('Kamyaran','Kamyaran'),
    ('Kangavar','Kangavar'),
    ('Karaj','Karaj'),
    ('Kashan','Kashan'),
    ('Kashmar','Kashmar'),
    ('Kavar','Kavar'),
    ('Kazerun','Kazerun'),
    ('Kelishad Va Sudarjan','Kelishad Va Sudarjan'),
    ('Kerman','Kerman'),
    ('Kermanshah (Bakhtaran)','Kermanshah (Bakhtaran)'),
    ('Khalkhal','Khalkhal'),
    ('Khash','Khash'),
    ('Khomeyn','Khomeyn'),
    ('Khomeyni Shahr (Homayunshahr)','Khomeyni Shahr (Homayunshahr)'),
    ('Khoram Abad','Khoram Abad'),
    ('Khoramdareh [Khorramdarreh]','Khoramdareh [Khorramdarreh]'),
    ('Khoramshahr (Khuninshahr)','Khoramshahr (Khuninshahr)'),
    ('Khurmuj','Khurmuj'),
    ('Khuy [Khoy]','Khuy [Khoy]'),
    ('Khvaf','Khvaf'),
    ('Khvorzuq','Khvorzuq'),
    ('Kish','Kish'),
    ('Konarak','Konarak'),
    ('Kordkuy','Kordkuy'),
    ('Kuhdasht','Kuhdasht'),
    ('Kut-E Abdallah','Kut-E Abdallah'),
    ('Lahijan','Lahijan'),
    ('Lamerd','Lamerd'),
    ('Langarud','Langarud'),
    ('Lar','Lar'),
    ('Lordegan','Lordegan'),
    ('Mahabad','Mahabad'),
    ('Maḥalat [Mahallat]','Maḥalat [Mahallat]'),
    ('Mahdasht','Mahdasht'),
    ('Maḥmud-Abad','Maḥmud-Abad'),
    ('Maku','Maku'),
    ('Malard','Malard'),
    ('Malayer','Malayer'),
    ('Malekan','Malekan'),
    ('Maragheh','Maragheh'),
    ('Marand','Marand'),
    ('Marivan','Marivan'),
    ('Marvdasht','Marvdasht'),
    ('Mashhad','Mashhad'),
    ('Masjed-E Soleyman','Masjed-E Soleyman'),
    ('Mehriz','Mehriz'),
    ('Meshgin Shahr','Meshgin Shahr'),
    ('Meshkin Dasht','Meshkin Dasht'),
    ('Meybod','Meybod'),
    ('Mianduab [Miandoab]','Mianduab [Miandoab]'),
    ('Mianeh','Mianeh'),
    ('Minab','Minab'),
    ('Minudasht','Minudasht'),
    ('Mobarakeh','Mobarakeh'),
    ('Moḥamadiyeh','Moḥamadiyeh'),
    ('Moḥamadshahr','Moḥamadshahr'),
    ('Nahavand','Nahavand'),
    ('Na-In [Naeen]','Na-In [Naeen]'),
    ('Najaf Abad','Najaf Abad'),
    ('Naqadeh','Naqadeh'),
    ('Nasim Shahr (Akbarabad)','Nasim Shahr (Akbarabad)'),
    ('Nasirshahr','Nasirshahr'),
    ('Naẓar-Abad','Naẓar-Abad'),
    ('Neka','Neka'),
    ('Neyriz','Neyriz'),
    ('Nishabur [Nishapur]','Nishabur [Nishapur]'),
    ('Nowshahr','Nowshahr'),
    ('Nur','Nur'),
    ('Nur-Abad','Nur-Abad'),
    ('Nur-Abad','Nur-Abad'),
    ('Omidiyeh','Omidiyeh'),
    ('Orumiyeh (Reza-Iyeh) [Urmia]','Orumiyeh (Reza-Iyeh) [Urmia]'),
    ('Oshnavieh','Oshnavieh'),
    ('Pakdasht','Pakdasht'),
    ('Parand','Parand'),
    ('Pardis','Pardis'),
    ('Pars Abad','Pars Abad'),
    ('Paveh','Paveh'),
    ('Piranshahr','Piranshahr'),
    ('Pishva','Pishva'),
    ('Pol-E Dokhtar','Pol-E Dokhtar'),
    ('Qa-Emiyeh','Qa-Emiyeh'),
    ('Qa-Em Shahr','Qa-Em Shahr'),
    ('Qa-En','Qa-En'),
    ('Qahderijan','Qahderijan'),
    ('Qarah Ziya-Aldin','Qarah Ziya-Aldin'),
    ('Qarchak','Qarchak'),
    ('Qazvin','Qazvin'),
    ('Qeshm','Qeshm'),
    ('Qeydar','Qeydar'),
    ('Qods','Qods'),
    ('Qom','Qom'),
    ('Qorveh','Qorveh'),
    ('Quchan','Quchan'),
    ('Rafsanjan','Rafsanjan'),
    ('Ramhormoz','Ramhormoz'),
    ('Ramsar','Ramsar'),
    ('Ramshir','Ramshir'),
    ('Rasht','Rasht'),
    ('Robat Karim','Robat Karim'),
    ('Rudehen','Rudehen'),
    ('Rudsar','Rudsar'),
    ('Sabashahr (Qasemabad)','Sabashahr (Qasemabad)'),
    ('Sabzevar','Sabzevar'),
    ('Safadasht','Safadasht'),
    ('Safashahr','Safashahr'),
    ('Sahand','Sahand'),
    ('Saḥneh','Saḥneh'),
    ('Saleḥieh [Saleḥabad]','Saleḥieh [Saleḥabad]'),
    ('Salmas','Salmas'),
    ('Sanandaj','Sanandaj'),
    ('Saqqez','Saqqez'),
    ('Sarab','Sarab'),
    ('Sarakhs','Sarakhs'),
    ('Saravan','Saravan'),
    ('Sardasht','Sardasht'),
    ('Sardrud','Sardrud'),
    ('Sari','Sari'),
    ('Sarpol-E Dhahab [Sarpol-E Zahab]','Sarpol-E Dhahab [Sarpol-E Zahab]'),
    ('Saveh','Saveh'),
    ('Semirom','Semirom'),
    ('Semnan','Semnan'),
    ('Shadegan','Shadegan'),
    ('Shahedshahr','Shahedshahr'),
    ('Shahin Dezh','Shahin Dezh'),
    ('Shahin Shahr','Shahin Shahr'),
    ('Shahr-E Babak','Shahr-E Babak'),
    ('Shahr-E Jadid-E Hashtgerd','Shahr-E Jadid-E Hashtgerd'),
    ('Shahr-E Kord','Shahr-E Kord'),
    ('Shahr-E Sadra','Shahr-E Sadra'),
    ('Shahreza (Qomsheh) []','Shahreza (Qomsheh) [Shahreza]'),
    ('Shahriar','Shahriar'),
    ('Shahrud ','Shahrud '),
    ('Sheybani','Sheybani'),
    ('Shiraz','Shiraz'),
    ('Shirvan','Shirvan'),
    ('Showt','Showt'),
    ('Shush','Shush'),
    ('Shushtar','Shushtar'),
    ('Sirjan','Sirjan'),
    ('Sonqor','Sonqor'),
    ('Sowme-Eh Sara','Sowme-Eh Sara'),
    ('Susangerd','Susangerd'),
    ('Tabas','Tabas'),
    ('Tabriz','Tabriz'),
    ('Takab','Takab'),
    ('Takestan','Takestan'),
    ('Taybad','Taybad'),
    ('Tehran','Tehran'),
    ('Tonekabon','Tonekabon'),
    ('Torbat-E Ḥeydarieh','Torbat-E Ḥeydarieh'),
    ('Torbat-E Jam','Torbat-E Jam'),
    ('Tuyserkan','Tuyserkan'),
    ('Vaḥidieh','Vaḥidieh'),
    ('Varamin','Varamin'),
    ('Yasuj','Yasuj'),
    ('Yazd','Yazd'),
    ('Zabol','Zabol'),
    ('Zahedan','Zahedan'),
    ('Zanjan','Zanjan'),
    ('Zarand','Zarand'),
    ('Zarin Shahr','Zarin Shahr'),
    ('Zarqan','Zarqan'),
)

yearList = (
    (1360,1360),
    (1361,1361),
    (1362,1362),
    (1363,1363),
    (1364,1364),
    (1365,1365),
    (1366,1366),
    (1367,1367),
    (1368,1368),
    (1369,1369),
    (1370,1370),
    (1371,1371),
    (1372,1372),
    (1373,1373),
    (1374,1374),
    (1375,1375),
    (1376,1376),
    (1377,1377),
    (1378,1378),
    (1379,1379),
    (1380,1380),
    (1381,1381),
    (1382,1382),
    (1383,1383),
    (1384,1384),
    (1385,1385),
    (1386,1386),
    (1387,1387),
    (1388,1388),
    (1389,1389),
    (1390,1390),
    (1391,1391),
    (1392,1392),
    (1393,1393),
    (1394,1394),
    (1395,1395),
    (1396,1396),

)
mounthList =(
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
    (6,6),
    (7,7),
    (8,8),
    (9,9),
    (10,10),
    (11,11),
    (12,12),
)
dayList =(
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
    (6,6),
    (7,7),
    (8,8),
    (9,9),
    (10,10),
    (11,11),
    (12,12),
    (13,13),
    (14,14),
    (15,15),
    (16,16),
    (17,17),
    (18,18),
    (19,19),
    (20,20),
    (21,21),
    (22,22),
    (23,23),
    (24,24),
    (25,25),
    (26,26),
    (27,27),
    (28,28),
    (29,29),
    (30,30),
    (31,31),
    
)



class Profile(AbstractBaseUser):
    isf_id          = models.BigIntegerField(unique=True )
    first_name      = models.CharField(max_length=255)
    last_name       = models.CharField(max_length=255)
    email           = models.EmailField(blank=True, null=True)
    country_names   = CountryField(default="IR",blank_label='(select country)')
    city_name       = models.CharField(max_length=250,null=True,blank=True,choices=cityList,default='Tehran')
    phone_number    = models.BigIntegerField(blank=True,null=True)
    profile_image   = models.ImageField(upload_to='profile',blank=True, null=True)
    judge           = models.BooleanField(default=False)
    player          = models.BooleanField(default=False)
    admin           = models.BooleanField(default=False)
    active          = models.BooleanField(default=True)
    staff           = models.BooleanField(default=False)
    club            = models.CharField(max_length=250, blank=True, null=True)
    cridit_card     = models.BigIntegerField(blank=True, null=True)
    id_number       = models.BigIntegerField(blank=True, null=True)
    year            = models.IntegerField(blank=True, null=True,choices=yearList)
    mounth          = models.IntegerField(blank=True, null=True,choices=mounthList)
    day             = models.IntegerField(blank=True, null=True,choices=dayList)


    USERNAME_FIELD  = 'isf_id'
    REQUIRED_FIELDS = ['first_name','last_name']
    objects         = ProfileManager()

    def __str__(self):
        return self.first_name + " | " + self.last_name

    def has_perm(self,perm,obj = None):
        return True
    def has_module_perms(self,app_label):
        return True

    
    
         
    

    @property
    def is_active(self):
        return self.active
    @property
    def is_staff(self):
        return self.staff
    @property
    def is_admin(self):
        return self.admin
    @property
    def is_player(self):
        return self.player
    @property
    def is_judge(self):
        return self.judge
    





