# Generated by Django 3.0.3 on 2020-04-04 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point_app', '0001_initial'),
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pic')),
                ('year', models.IntegerField()),
                ('mounth', models.IntegerField()),
                ('day', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.Category')),
                ('head_judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to=settings.AUTH_USER_MODEL)),
                ('judges', models.ManyToManyField(related_name='judges', to=settings.AUTH_USER_MODEL)),
                ('point_system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_app.Point')),
            ],
        ),
    ]
