# Generated by Django 3.0.3 on 2020-04-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatition_app', '0003_auto_20200408_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
