# Generated by Django 3.0.3 on 2020-04-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
