# Generated by Django 3.0.3 on 2020-04-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank_app', '0002_rank_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='age',
            new_name='category_age',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='gender',
            new_name='category_gender',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='player',
            new_name='player_id',
        ),
    ]
