# Generated by Django 3.0.3 on 2020-04-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_app', '0004_auto_20200408_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='best',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
