# Generated by Django 3.0.3 on 2020-04-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank_app', '0005_auto_20200408_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='best',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='total',
        ),
    ]
